apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apiworker
  namespace: infra
spec:
  chart:
    spec:
      chart: ./hlm/apiworker
      sourceRef:
        kind: GitRepository
        name: apiworker
        namespace: infra
  install:
    remediation:
      retries: -1
  interval: 1m
  values:
    image:
      tag: 5b8392b53c1a777c882332541c3bbe9f59023d27
