apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "webclient"
  namespace: "infra"
spec:
  chart:
    spec:
      chart: "./hlm/webclient"
      sourceRef:
        kind: "GitRepository"
        name: "webclient"
        namespace: "infra"
  install:
    remediation:
      retries: -1
  interval: "1m"
  values:
    api:
      endpoint: "https://apiserver.kia06.aws.venturemark.co:443"
    cluster:
      name: "kia06"
      zone: "aws.venturemark.co"
    image:
      tag: "e5eaccfe55e4283394173b1e25e578cbfdbe3228"
