apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "redis-failover"
  namespace: "infra"
spec:
  chart:
    spec:
      chart: "./hlm/redis-failover"
      sourceRef:
        kind: "GitRepository"
        name: "redis"
        namespace: "infra"
  dependsOn:
    - "release-operator"
  interval: "1m"
  values:
    image:
      tag: "5d255b7fea6a345b02242e0833e973d4f0bad061"
---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "redis-operator"
  namespace: "infra"
spec:
  chart:
    spec:
      chart: "./hlm/redis-operator"
      sourceRef:
        kind: "GitRepository"
        name: "redis"
        namespace: "infra"
  interval: "1m"
  values:
    image:
      tag: "5d255b7fea6a345b02242e0833e973d4f0bad061"
