apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "redis-failover"
  namespace: "infra"
spec:
  chart:
    spec:
      chart: "./hlm/redis-failover"
      sourceRef:
        kind: "GitRepository"
        name: "redis"
        namespace: "infra"
  dependsOn:
    - name: "release-operator"
  interval: "1m"
---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "redis-operator"
  namespace: "infra"
spec:
  chart:
    spec:
      chart: "./hlm/redis-operator"
      sourceRef:
        kind: "GitRepository"
        name: "redis"
        namespace: "infra"
  interval: "1m"
