apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apiworker
  namespace: infra
spec:
  chart:
    spec:
      chart: ./hlm/apiworker
      sourceRef:
        kind: GitRepository
        name: apiworker
        namespace: infra
  install:
    remediation:
      retries: -1
  interval: 1m
  values:
    image:
      tag: edd048a3704b44c296034e244c5ce33299c98d09
