apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: "HelmRelease"
metadata:
  name: "webclient"
  namespace: "infra"
spec:
  chart:
    spec:
      chart: "./hlm/webclient"
      sourceRef:
        kind: "GitRepository"
        name: "webclient"
        namespace: "infra"
  install:
    remediation:
      retries: -1
  interval: "1m"
  values:
    api:
      endpoint: "https://apiserver.kia07.aws.venturemark.co:443"
    cluster:
      name: "kia07"
      zone: "aws.venturemark.co"
    dns:
      cname: "alpha.venturemark.co"
    image:
      tag: "8d047786dfd0ea75e1af051c6b001305e1da4bf4"
