apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webclient
  namespace: infra
spec:
  chart:
    spec:
      chart: ./hlm/webclient
      sourceRef:
        kind: GitRepository
        name: webclient
        namespace: infra
  install:
    remediation:
      retries: -1
  interval: 1m
  values:
    api:
      endpoint: https://apiserver.kia07.aws.breadcrumb.so:443
    cluster:
      name: kia07
      zone: aws.breadcrumb.so
    dns:
      cname: beta.breadcrumb.so
    image:
      tag: 4644424f4a3a46af397276fab860055a61afb9b0
