apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webclient
  namespace: infra
spec:
  chart:
    spec:
      chart: ./hlm/webclient
      sourceRef:
        kind: GitRepository
        name: webclient
        namespace: infra
  install:
    remediation:
      retries: -1
  interval: 1m
  values:
    api:
      endpoint: https://apiserver.kia07.aws.venturemark.co:443
    cluster:
      name: kia07
      zone: aws.venturemark.co
    dns:
      cname: beta.venturemark.co
    image:
      tag: 03327f68d5525b36e92ba8dfb29e8e15aae4c5f5
